// Mocks generated by Mockito 5.4.1 from annotations
// in products_task/test/features/Products/repository/impl/products_repository_impl_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:products_task/core/constants/params.dart' as _i4;
import 'package:products_task/features/Products/data/base/base_local_products_data_source.dart'
    as _i2;
import 'package:products_task/features/Products/model/products_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BaseLocalProductsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLocalProductsDataSource extends _i1.Mock
    implements _i2.BaseLocalProductsDataSource {
  MockBaseLocalProductsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initDataBase(_i4.InitDatabaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #initDataBase,
          [params],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<int> insertProduct(_i4.InsertProductParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [params],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<List<_i5.ProductsModel>> getAllProducts(
          _i4.GetAllProductsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [params],
        ),
        returnValue:
            _i3.Future<List<_i5.ProductsModel>>.value(<_i5.ProductsModel>[]),
      ) as _i3.Future<List<_i5.ProductsModel>>);
  @override
  _i3.Future<int> updateProduct(_i4.UpdateProductParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [params],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<int> deleteProduct(_i4.DeleteProductParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [params],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
