on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
  build_macos:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.2'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk
      - name: Get Release Assets
        id: release_assets
        run: |
          RELEASE_ID=$(curl -s -X GET -u ${{ secrets.TOKEN }} "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r '.id')
          ASSETS=$(curl -s -X GET -u ${{ secrets.TOKEN }} "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets" | jq -r '.[].browser_download_url')

          echo "::set-output name=ANDROID_DOWNLOAD_LINK::$(echo "$ASSETS" | grep 'app-armeabi-v7a-debug.apk$')"
          echo "::set-output name=IOS_DOWNLOAD_LINK::$(echo "$ASSETS" | grep 'app.ipa$')"

      - name: Send Email Notifications
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ahmedmohamedah731@gmail.com
          to: anaahmedmohamed57@gmail.com
          subject: "Build Successful - Download Links"
          body: |
            Hi there,
            
            Your app build was successful! Here are the download links:
            
            Android APK: ${{ steps.release_assets.outputs.ANDROID_DOWNLOAD_LINK }}
            iOS IPA: ${{ steps.release_assets.outputs.IOS_DOWNLOAD_LINK }}
            
            Best regards,
            Your App Team
  build-linux:

    needs: build_macos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: products
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers
          file: /home/runner/work/products_task/products_task/build/app/outputs/apk/debugapp-armeabi-v7a-debug.apk
          notifyTesters: true
          debug: false
 
# push to master, main, develop
# pull request on main master 