on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
      - name: Send Email Notifications
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ahmedmohamedah731@gmail.com
          to: anaahmedmohamed57@gmail.com
          subject: "Build Successful - Download Links"
          body: |
            Hi there,
            
            Your app build was successful! Here are the download links:)
            
            Android APK: ${{ steps.release.outputs.android_download_link }}
            iOS IPA: ${{ steps.release.outputs.ios_download_link }}
            
            Best regards,
            Your App Team


# push to master, main, develop
# pull request on main master